/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ab_docSimilarity_main_HelloJNIWMD */

#ifndef _Included_com_ab_docSimilarity_main_HelloJNIWMD
#define _Included_com_ab_docSimilarity_main_HelloJNIWMD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ab_docSimilarity_main_HelloJNIWMD
 * Method:    computeDistance
 * Signature: ([D[D[[D)D
 */
JNIEXPORT jdouble JNICALL Java_com_ab_docSimilarity_main_HelloJNIWMD_computeDistance
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
